app/mod_admin/controllers.py
from functools import wraps

from flask import Blueprint, redirect, url_for, render_template, request
from flask_login import current_user, login_required

from app import db
from app.forms import CenterForm, CardForm, ActivityForm, MachineForm
from app.models import Activity, Card, Center, Check, Exercise, Machine, Measurement, User

mod_admin = Blueprint('admin', __name__, url_prefix='/admin')


def admin_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not current_user.admin:
            return redirect(url_for('dashboard.index'))
        return f(*args, **kwargs)
    return decorated_function


@mod_admin.route('/')
@login_required
@admin_required
def admin_center():
    amounts = []
    amounts.insert(len(amounts), {'entity': 'Activities', 'amount': db.session.query(Activity).count()})
    amounts.insert(len(amounts), {'entity': 'Cards', 'amount': db.session.query(Card).count()})
    amounts.insert(len(amounts), {'entity': 'Centers', 'amount': db.session.query(Center).count()})
    amounts.insert(len(amounts), {'entity': 'Checks', 'amount': db.session.query(Check).count()})
    amounts.insert(len(amounts), {'entity': 'Exercises', 'amount': db.session.query(Exercise).count()})
    amounts.insert(len(amounts), {'entity': 'Machines', 'amount': db.session.query(Machine).count()})
    amounts.insert(len(amounts), {'entity': 'Measurements', 'amount': db.session.query(Measurement).count()})
    amounts.insert(len(amounts), {'entity': 'Users', 'amount': db.session.query(User).count()})
    return render_template('admin/admin_center.html', amounts=amounts)


@mod_admin.route('/centers')
@login_required
@admin_required
def centers():
    return render_template('admin/centers.html', db=db, Center=Center)


@mod_admin.route('/centers/add', methods=['GET', 'POST'])
@login_required
@admin_required
def add_center():
    form = CenterForm(request.form)
    if request.method == 'POST' and form.validate():
        center = Center(name=form.name.data,
                        street=form.street.data,
                        house_number=form.house_number.data,
                        zip_code=form.zip_code.data,
                        city=form.city.data)
        db.session.add(center)
        db.session.commit()
        return redirect(url_for('admin.centers'))
    return render_template('admin/add/center.html', form=form, callback=url_for('admin.add_center'))


@mod_admin.route('/centers/edit/<int:center_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_center(center_id):
    center = db.session.query(Center).filter_by(center_id=center_id).first()
    form = CenterForm(request.form, center)
    if request.method == 'POST' and form.validate():
        form.populate_obj(center)
        db.session.commit()
        return redirect(url_for('admin.centers'))
    return render_template('admin/add/center.html', form=form, callback=url_for('admin.edit_center',
                                                                                center_id=center_id))


@mod_admin.route('/centers/delete/<int:center_id>')
@login_required
@admin_required
def delete_center(center_id):
    center = db.session.query(Center).filter_by(center_id=center_id).first()
    db.session.delete(center)
    db.session.commit()
    return redirect(url_for('admin.centers'))


@mod_admin.route('/checks')
@login_required
@admin_required
def checks():
    return render_template('admin/checks.html', db=db, Check=Check)


@mod_admin.route('/cards')
@login_required
@admin_required
def cards():
    return render_template('admin/card.html', db=db, Card=Card)


@mod_admin.route('/cards/add', methods=['GET', 'POST'])
@login_required
@admin_required
def add_card():
    form = CardForm(request.form)
    form.user_id.choices = [(user.user_id, user.construct_name()) for user in db.session.query(User).all()]
    if request.method == 'POST' and form.validate():
        card = Card(user_id=form.user_id.data,
                    active=True)
        user = db.session.query(User).filter_by(user_id=form.user_id.data).first()
        user.cards.append(card)
        db.session.add(card)
        db.session.commit()
        return redirect(url_for('admin.cards'))
    return render_template('admin/add/card.html', form=form)


@mod_admin.route('/activities')
@login_required
@admin_required
def activities():
    return render_template('admin/activities.html', db=db, Activity=Activity)


@mod_admin.route('/activities/add', methods=['GET', 'POST'])
@login_required
@admin_required
def add_activity():
    form = ActivityForm(request.form)
    if request.method == 'POST' and form.validate():
        activity = Activity(name=form.name.data)
        db.session.add(activity)
        db.session.commit()
        return redirect(url_for('admin.activities'))
    return render_template('admin/add/activity.html', form=form)


@mod_admin.route('/machines')
@login_required
@admin_required
def machines():
    return render_template('admin/machines.html', db=db, Machine=Machine)


@mod_admin.route('/machines/add', methods=['GET', 'POST'])
@login_required
@admin_required
def add_machine():
    form = MachineForm(request.form)
    form.activity_id.choices = [(activity.activity_id, activity.name) for activity in db.session.query(Activity).all()]
    form.center_id.choices = [(center.center_id, center.name) for center in db.session.query(Center).all()]
    if request.method == 'POST' and form.validate():
        machine = Machine(
            activity_id=form.activity_id.data,
            center_id=form.center_id.data
        )
        center = db.session.query(Center).filter_by(center_id=form.center_id.data).first()
        activity = db.session.query(Activity).filter_by(activity_id=form.activity_id.data).first()
        center.machines.append(machine)
        activity.machines.append(machine)
        db.session.add(machine)
        db.session.commit()
        return redirect(url_for('admin.machines'))
    return render_template('admin/add/machine.html', form=form)


@mod_admin.route('/users')
@login_required
@admin_required
def users():
    return render_template('admin/users.html', db=db, User=User)

app/mod_auth/controllers.py
import flask
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, login_required, logout_user
from werkzeug.security import generate_password_hash, check_password_hash

from app import User, db
from app.forms import RegisterForm, LoginForm

mod_auth = Blueprint('auth', __name__)


@mod_auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        admin = False
        if db.session.query(User).count() == 0:
            admin = True
        user = User(first_name=form.first_name.data,
                    last_name=form.last_name.data,
                    street=form.street.data,
                    house_number=form.house_number.data,
                    zip_code=form.zip_code.data,
                    city=form.city.data,
                    phone_number=form.phone_number.data,
                    email=form.email.data,
                    password=generate_password_hash(form.password.data),
                    admin=admin
                    )
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('auth.login'))
    return render_template('auth/register.html', form=form)


@mod_auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        user = db.session.query(User).filter_by(email=form.email.data).first()
        if not user:
            form.email.errors.append('Geen gebruiker met dit email adres gevonden')
            return render_template('auth/login.html', form=form)
        if check_password_hash(user.password, form.password.data):
            login_user(user)
            return redirect(url_for('dashboard.index'))
        else:
            form.password.errors.append('Wachtwoord in incorrect')
            return render_template('auth/login.html', form=form)
    return render_template('auth/login.html', form=form)


@mod_auth.route('/signout', methods=['GET', 'POST'])
@login_required
def signout():
    logout_user()
    return redirect(url_for('auth.login'))


@mod_auth.route('/home', methods=['GET', 'POST'])
def home():
    return redirect(url_for('auth.login'))

app/mod_dashboard/controllers.py
import datetime
from functools import wraps

import math
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user

from app import db
from app.forms import MeasurementForm, EditForm
from app.models import Activity, Card, Center, Check, Exercise, Machine, Measurement, User

mod_dashboard = Blueprint('dashboard', __name__)


@mod_dashboard.route('/')
@login_required
def index():
    amounts = []
    amounts.insert(len(amounts), {'entity': 'Activities', 'amount': db.session.query(Activity).count()})
    amounts.insert(len(amounts), {'entity': 'Cards', 'amount': db.session.query(Card).count()})
    amounts.insert(len(amounts), {'entity': 'Centers', 'amount': db.session.query(Center).count()})
    amounts.insert(len(amounts), {'entity': 'Checks', 'amount': db.session.query(Check).count()})
    amounts.insert(len(amounts), {'entity': 'Exercises', 'amount': db.session.query(Exercise).count()})
    amounts.insert(len(amounts), {'entity': 'Machines', 'amount': db.session.query(Machine).count()})
    amounts.insert(len(amounts), {'entity': 'Measurements', 'amount': db.session.query(Measurement).count()})
    amounts.insert(len(amounts), {'entity': 'Users', 'amount': db.session.query(User).count()})
    return render_template('dashboard/index.html', amounts=amounts)


@mod_dashboard.route('/gewicht')
@login_required
def measurements():
    return render_template('dashboard/measurements.html', db=db, Measurement=Measurement)


@mod_dashboard.route('/gewicht/add', methods=['GET', 'POST'])
@login_required
def add_measurement():
    form = MeasurementForm(request.form)
    if request.method == 'POST' and form.validate():
        measurement = Measurement(
            weight=form.weight.data,
            height=form.height.data,
            date=datetime.date.today()
        )
        current_user.measurements.append(measurement)
        db.session.add(measurement)
        db.session.commit()
        return redirect(url_for('dashboard.measurements'))
    elif request.method == 'GET':
        last_measurement = db.session.query(Measurement)\
            .order_by(Measurement.measure_id.desc())\
            .filter_by(user_id=current_user.user_id)\
            .first()
        if last_measurement:
            form = MeasurementForm(weight=last_measurement.weight, height=last_measurement.height)
        return render_template('dashboard/add/measurement.html', form=form)
    return render_template('dashboard/add/measurement.html', form=form)


@mod_dashboard.route('/statistiek')
@login_required
def stats():
    stat = {}
    count = {}
    for exercise in current_user.exercises:
        date = exercise.datetime.strftime('%m/%Y')
        if date in stat:
            stat[date]['time_active'] += float("{0:.2f}".format(exercise.time))
            stat[date]['burnt_calories'] += float("{0:.2f}".format(exercise.burnt_calories))
        else:
            stat[date] = {}
            stat[date]['time_active'] = float("{0:.2f}".format(exercise.time))
            stat[date]['burnt_calories'] = float("{0:.2f}".format(exercise.burnt_calories))
            stat[date]['visits'] = 0
        if exercise.machine.activity.name in count:
            count[exercise.machine.activity.name] += 1
        else:
            count[exercise.machine.activity.name] = 1
    for card in current_user.cards:
        for check in card.checks:
            if check.in_out:
                date = check.time.strftime('%m/%Y')
                if date in stat:
                    stat[date]['visits'] += 1
                else:
                    stat[date] = {}
                    stat[date]['visits'] = 1
    return render_template('dashboard/statistics.html', db=db, Exercise=Exercise, stats=stat, count=count)


@mod_dashboard.route('/activiteit')
@login_required
def activities():
    return render_template('dashboard/exercises.html', db=db, Exercise=Exercise, math=math)


@mod_dashboard.route('/edit_user', methods=['GET', 'POST'])
@login_required
def edit_user():
    form = EditForm(request.form, current_user)
    if request.method == 'POST' and form.validate():
        form.populate_obj(current_user)
        db.session.commit()
        return redirect(url_for('dashboard.index'))
    return render_template('dashboard/edit_user.html', form=form)

app/templates/dashboard/edit_user.html
{% extends 'dashboard/layout.html' %}
{% import 'macros.html' as macros %}
{% block main %}
    <div class="mdl-grid">
        <div class="mdl-cell--4-col"></div>
        <div class="mdl-cell--4-col">
            <form method="POST" action="{{ url_for('dashboard.edit_user') }}">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    {{ macros.generate_input(form.street) }}
                </div><br>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    {{ macros.generate_input(form.house_number) }}
                </div><br>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    {{ macros.generate_input(form.zip_code) }}
                </div><br>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    {{ macros.generate_input(form.city) }}
                </div><br>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    {{ macros.generate_input(form.phone_number) }}
                </div><br><br>
                <div>
                    <input type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" name="submit">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

app/templates/dashboard/exercises.html
{% extends 'dashboard/layout.html' %}
{% block header_title %}
    Activiteiten
{% endblock %}
{% block title %}
    Activiteiten
{% endblock %}
{% block main %}
    <div class="margin">
        <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
            <thead>
            <tr>
                <th class="mdl-data-table__cell--non-numeric">Activiteit</th>
                <th class="mdl-data-table__cell--non-numeric">Totale tijd</th>
                <th class="mdl-data-table__cell--non-numeric">Verbrande Calorieen</th>
                <th class="mdl-data-table__cell--non-numeric">Gemiddelde Snelheid</th>
                <th class="mdl-data-table__cell--non-numeric">Sportschool</th>
            </tr>
            </thead>
            <tbody>
            {% for exercise in current_user.exercises %}
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">{{ exercise.machine.activity.name }}</td>
                    {% if exercise.time > 60 %}
                        {% set time = exercise.time %}
                        {% set minutes = math.floor(exercise.time / 60) %}
                        {% set seconds = time - 60 * minutes %}
                        <td class="mdl-data-table__cell--non-numeric">{{ minutes }} m {{ seconds }} sec</td>
                    {% else %}
                        <td class="mdl-data-table__cell--non-numeric">{{ exercise.time }} sec</td>
                    {% endif %}
                    <td class="mdl-data-table__cell--non-numeric">{{ "{0:.2f}".format(exercise.burnt_calories) }}</td>
                    <td class="mdl-data-table__cell--non-numeric">{{ exercise.constant.speed or '--' }} km/h</td>
                    <td class="mdl-data-table__cell--non-numeric">{{ exercise.machine.center.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

app/templates/dashboard/index.html
{% extends 'dashboard/layout.html' %}
{% block title %}
    Dashboard
{% endblock %}
{% block header_title %}
    Dashboard
{% endblock %}
{% block main %}
    <div class="mdl-grid demo-content">
        <div class="demo-card-wide mdl-card mdl-shadow--2dp mdl-cell" style="min-height: 0;">
            <div class="mdl-card__title">
                <h2 class="mdl-card__title-text">Statistieken</h2>
            </div>
            <div class="mdl-card__supporting-text">
                Bekijk nu uw sportprestaties terug in handige grafieken
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" href="{{ url_for('dashboard.stats') }}">
                    Bekijken
                </a>
            </div>
        </div>
        <div class="demo-card-wide mdl-card mdl-shadow--2dp mdl-cell" style="min-height: 0;">
            <div class="mdl-card__title">
                <h2 class="mdl-card__title-text">Gewicht</h2>
            </div>
            <div class="mdl-card__supporting-text">
                Zie vooruitgang in het afvallen, door uw gewicht actueel te houden, wordt alles goed berekent.
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" href="{{ url_for('dashboard.measurements') }}">
                    Bekijken
                </a>
            </div>
        </div>
        <div class="demo-card-wide mdl-card mdl-shadow--2dp mdl-cell" style="min-height: 0;">
            <div class="mdl-card__title">
                <h2 class="mdl-card__title-text">Activiteit</h2>
            </div>
            <div class="mdl-card__supporting-text">
                Bekijk nu uw sportprestaties terug in een overzichtelijke tabel
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" href="{{ url_for('dashboard.activities') }}">
                    Bekijken
                </a>
            </div>
        </div>
        <div class="demo-card-wide mdl-card mdl-shadow--2dp mdl-cell" style="min-height: 0;">
            <div class="mdl-card__title">
                <h2 class="mdl-card__title-text">Uw Gegevens</h2>
            </div>
            <div class="mdl-card__supporting-text">
                {{ current_user.construct_name() }}<br>
                {{ current_user.street }} {{ current_user.house_number }}<br>
                {{ current_user.zip_code }}<br>
                {{ current_user.city }}<br>
                {{ current_user.phone_number }}<br>
                {{ current_user.email }}<br>
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" href="{{ url_for('dashboard.edit_user') }}">
                    Bewerken
                </a>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/dashboard/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="images/android-desktop.png">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Material Design Lite">
    <link rel="apple-touch-icon-precomposed" href="images/ios-desktop.png">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
    <meta name="msapplication-TileColor" content="#3372DF">

    <link rel="shortcut icon" href="images/favicon.png">
    {% assets "dashboard_css" %}
        <link rel="stylesheet" href="{{ ASSET_URL }}" />
    {% endassets %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    {% block head %}

    {% endblock %}
</head>
<body>
<div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
    <header class="demo-header mdl-layout__header">
        <div class="mdl-layout__header-row">
            <span class="mdl-layout-title">{% block header_title %}{% endblock %}</span>
            <div class="mdl-layout-spacer"></div>
        </div>
    </header>
    <div class="demo-drawer mdl-layout__drawer mdl-color--amber-400 mdl-color-text--blue-grey-900">
        <header class="demo-drawer-header">
            <img src="static/img/bravo_logo.png" class="demo-avatar">
            <div class="demo-avatar-dropdown">
                <span>{{ current_user.construct_name() }}</span>
                <div class="mdl-layout-spacer"></div>
            </div>
        </header>
        <nav class="demo-navigation mdl-navigation mdl-color--amber-50">
            <a class="mdl-navigation__link mdl-color-text--blue-grey-600" href="{{ url_for('dashboard.index') }}"><i class="mdl-color-text--blue-400 material-icons" role="presentation">home</i>Home</a>
            <a class="mdl-navigation__link mdl-color-text--blue-grey-600" href="{{ url_for('dashboard.stats') }}"><i class="mdl-color-text--blue-400 material-icons" role="presentation">assessment</i>Statistieken</a>
            <a class="mdl-navigation__link mdl-color-text--blue-grey-600" href="{{ url_for('dashboard.measurements') }}"><i class="mdl-color-text--blue-400 material-icons" role="presentation">trending_down</i>Gewicht</a>
            <a class="mdl-navigation__link mdl-color-text--blue-grey-600" href="{{ url_for('dashboard.activities') }}"><i class="mdl-color-text--blue-400 material-icons" role="presentation">fitness_center</i>Activiteit</a>
            {% if current_user.admin %}
                <div class="seperator"></div>
                <a class="mdl-navigation__link mdl-color-text--blue-600" href="{{ url_for('admin.admin_center') }}"><i class="mdl-color-text--blue-400 material-icons" role="presentation">developer_board</i>Admin Center</a>
                <a class="mdl-navigation__link mdl-color-text--blue-grey-600" href="{{ url_for('admin.centers') }}"><i class="mdl-color-text--blue-400 material-icons" role="presentation">domain</i>Fitness Centers</a>
                <a class="mdl-navigation__link mdl-color-text--blue-grey-600" href="{{ url_for('admin.cards') }}"><i class="mdl-color-text--blue-400 material-icons" role="presentation">credit_card</i>Kaartbeheer</a>
                <a class="mdl-navigation__link mdl-color-text--blue-grey-600" href="{{ url_for('admin.checks') }}"><i class="mdl-color-text--blue-400 material-icons" role="presentation">import_export</i>Transactiebeheer</a>
                <a class="mdl-navigation__link mdl-color-text--blue-grey-600" href="{{ url_for('admin.activities') }}"><i class="mdl-color-text--blue-400 material-icons" role="presentation">pool</i>Activiteitbeheer</a>
                <a class="mdl-navigation__link mdl-color-text--blue-grey-600" href="{{ url_for('admin.machines') }}"><i class="mdl-color-text--blue-400 material-icons" role="presentation">fitness_center</i>Machinebeheer</a>
                <a class="mdl-navigation__link mdl-color-text--blue-grey-600" href="{{ url_for('admin.users') }}"><i class="mdl-color-text--blue-400 material-icons" role="presentation">person</i>Gebruikers</a>
            {% endif %}
            <div class="mdl-layout-spacer"></div>
            <a class="mdl-navigation__link mdl-color-text--blue-grey-600" href="mailto:benno@sportschool.nl"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">email</i><span class="visuallyhidden">Advies</span></a>
            <a class="mdl-navigation__link mdl-color-text--blue-grey-600" href="{{ url_for('auth.signout') }}"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">power_settings_new</i><span class="visuallyhidden">Uitloggen</span></a>


        </nav>
    </div>
    <main class="mdl-layout__content mdl-color--grey-100">
        {% block main %}{% endblock %}
    </main>
</div>
{% assets "dashboard_js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
</body>
</html>

app/templates/dashboard/measurements.html
{% extends 'dashboard/layout.html' %}
{% block header_title %}
    Gewicht
{% endblock %}
{% block title %}
    Gewicht
{% endblock %}
{% block head %}
    {% if current_user.measurements|length > 1 %}
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
        <script type="text/javascript">
            google.charts.load('current', {'packages':['line', 'table']});
            google.charts.setOnLoadCallback(drawChart);
            google.charts.setOnLoadCallback(drawTable);

            var dat = [{% for measurement in current_user.measurements %}
                {% set year = measurement.date.strftime('%Y') %}
                {% set month = measurement.date.strftime('%m')|int - 1 %}
                {% set day = measurement.date.strftime('%d') %}
                [new Date({{ year}}, {{month}}, {{day}}), {v: {{ measurement.weight }}, f: '{{ measurement.weight }} kg'}],
            {% endfor %}];
            function drawChart() {
                var data = new google.visualization.DataTable();
                data.addColumn('date', 'Datum');
                data.addColumn('number', 'Gewicht');
                data.addRows(dat);
                var container = document.getElementById('curve_chart');
                var options = {
                    title: 'Gewicht in kg',
                    curveType: 'function',
                    width: "100%",
                    height: "100%"
                };
                var chart = new google.charts.Line(container);
                chart.draw(data, options);
            }

            function drawTable() {
                var data = new google.visualization.DataTable();
                data.addColumn('date', 'Datum');
                data.addColumn('number', 'Gewicht');
                data.addRows(dat);
                var cssClassNames = {
                    'headerRow': '',
                    'tableRow': '',
                    'oddTableRow': '',
                    'selectedTableRow': 'a',
                    'hoverTableRow': '',
                    'headerCell': '',
                    'tableCell': '',
                    'rowNumberCell': ''
                };
                var options = {
                    width: '100%',
                    cssClassNames: cssClassNames
                };
                var table = new google.visualization.Table(document.getElementById('table_div'));

                google.visualization.events.addListener(table, "ready", materialize);
                table.draw(data, options);
            }

            function materialize() {
                var tab = document.getElementsByClassName('google-visualization-table-table')[0];
                tab.className = 'mdl-data-table mdl-js-data-table';
                tab.style = 'border:0; width:100%;';
                clear('google-visualization-table');
                clear('google-visualization-table-th');
                clear('google-visualization-table-td');
                clear('google-visualization-table-tr-head');
                clear('google-visualization-table-tr-even');
                clear('google-visualization-table-tr-odd');
                clear('google-visualization-table-type-date');
                function clear(className) {
                    var clearList = document.getElementsByClassName(className);
                    for (var i = 0; i < clearList.length; i++) {
                        clearList[i].className = '';
                    }
                }
            }
        </script>
    {% endif %}
{% endblock %}
{% block main %}
    <div class="mdl-grid">
        <div class="mdl-cell--8-col mdl-shadow--2dp mdl-cell mdl-card demo-card-wide">
            {% if current_user.measurements|length > 1 %}
                <div id="curve_chart" style="margin: 8px; height: 500px;"></div>
            {% else %}
                <div class="mdl-card__title">Nog niet genoeg data voor een grafiek</div>
            {% endif %}
        </div>
{#        <div class="mdl-cell--4-col mdl-shadow--2dp mdl-cell mdl-card demo-card-wide">#}
            <div id="table_div" class="mdl-cell--4-col mdl-cell mdl-card mdl-shadow--2dp"></div>
{#        </div>#}
    </div>
    <a href="{{ url_for('dashboard.add_measurement') }}" id="view-source" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
        <i class="material-icons">add</i>
    </a>
    <script>

    </script>
{% endblock %}